# Chapter 7

In [1]:
float_data = pd.Series([1.2, -3.5, np.nam, 0])

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
float_data = pd.Series([1.2, -3.5, np.nam, 0])

AttributeError: module 'numpy' has no attribute 'nam'

In [5]:
import pandas as pd
import numpy as np

In [6]:
In [14]: float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [7]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [8]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [9]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [10]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [11]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [12]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [13]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [14]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [ ]:
#dropna	Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.

In [ ]:
# fillna	Fill in missing data with some value or using an interpolation method such as "ffill" or "bfill".

In [ ]:
# isna	Return Boolean values indicating which values are missing/NA.

In [ ]:
# notna	Negation of isna, returns True for non-NA values and False for NA values.

In [15]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [16]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [19]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [20]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [22]:
data.dropna(how="all") #Passing how="all" will drop only rows that are all NA:

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# Keep in mind that these functions return new objects by default and do not modify the contents of the original object.

In [23]:
data[4] = np.nan

In [24]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [25]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [27]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [28]:
df.iloc[:4, 1] = np.nan

In [31]:
df.iloc[:2, 2] = np.nan

In [32]:
df

0         1         2
0 -0.540415       NaN       NaN
1  1.014800       NaN       NaN
2  0.072189       NaN -0.482249
3  0.405004       NaN  0.667234
4  0.899986  0.684868 -1.235916
5  1.092823  0.222275 -1.183510
6  0.797892  0.595294 -0.145587

In [33]:
df.dropna()

0         1         2
4  0.899986  0.684868 -1.235916
5  1.092823  0.222275 -1.183510
6  0.797892  0.595294 -0.145587

In [34]:
df.dropna(thresh=2)

0         1         2
2  0.072189       NaN -0.482249
3  0.405004       NaN  0.667234
4  0.899986  0.684868 -1.235916
5  1.092823  0.222275 -1.183510
6  0.797892  0.595294 -0.145587

In [35]:
df.fillna(0)

0         1         2
0 -0.540415  0.000000  0.000000
1  1.014800  0.000000  0.000000
2  0.072189  0.000000 -0.482249
3  0.405004  0.000000  0.667234
4  0.899986  0.684868 -1.235916
5  1.092823  0.222275 -1.183510
6  0.797892  0.595294 -0.145587

In [ ]:
# Calling fillna with a dictionary, you can use a different fill value for each column:

In [36]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.540415  0.500000  0.000000
1  1.014800  0.500000  0.000000
2  0.072189  0.500000 -0.482249
3  0.405004  0.500000  0.667234
4  0.899986  0.684868 -1.235916
5  1.092823  0.222275 -1.183510
6  0.797892  0.595294 -0.145587

In [39]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [46]:
df.iloc[2:, 1] = np.nan

In [44]:
df.iloc[4:, 2] = np.nan

In [47]:
df

0         1         2
0  0.315232 -0.366249 -0.969760
1 -0.210015 -1.708062 -0.230917
2 -0.743632       NaN  0.053430
3 -0.796544       NaN  0.041703
4 -0.499756       NaN       NaN
5 -1.076875       NaN       NaN

In [48]:
df.fillna(method="ffill")

/var/folders/cn/2lgryvj10c92k5wktj1wn8tr0000gp/T/ipykernel_71939/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.315232 -0.366249 -0.969760
1 -0.210015 -1.708062 -0.230917
2 -0.743632 -1.708062  0.053430
3 -0.796544 -1.708062  0.041703
4 -0.499756 -1.708062  0.041703
5 -1.076875 -1.708062  0.041703

In [49]:
df.fillna(method="ffill", limit=2)

/var/folders/cn/2lgryvj10c92k5wktj1wn8tr0000gp/T/ipykernel_71939/1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0  0.315232 -0.366249 -0.969760
1 -0.210015 -1.708062 -0.230917
2 -0.743632 -1.708062  0.053430
3 -0.796544 -1.708062  0.041703
4 -0.499756       NaN  0.041703
5 -1.076875       NaN  0.041703

In [50]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])


In [51]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [52]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})

In [53]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [54]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [55]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [56]:
data["v1"] = range(7)

In [57]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [58]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [59]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [60]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
   ....:                               "pastrami", "corned beef", "bacon",
   ....:                               "pastrami", "honey ham", "nova lox"],
   ....:                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})


In [61]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [62]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [63]:
data["animal"] = data["food"].map(meat_to_animal)

In [64]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [65]:
def get_animal(x):
    return meat_to_animal[x]

In [66]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [67]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [68]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [69]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [70]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [71]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [73]:
data.replace({-999: np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [75]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [76]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [77]:
def transform(x):
    return x[:4].upper()

In [78]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [79]:
data.index = data.index.map(transform)

In [80]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [81]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [82]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [95]:
bins = [18, 25, 35, 60, 100]

In [96]:
age_categories = pd.cut(ages, bins)

In [97]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [98]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [99]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [100]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [101]:
pd.value_counts(age_categories)

/var/folders/cn/2lgryvj10c92k5wktj1wn8tr0000gp/T/ipykernel_71939/3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [102]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [103]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [104]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [105]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [106]:
data = np.random.uniform(size=20)

In [107]:
pd.cut(data, 4, precision=2)

[(0.5, 0.75], (0.26, 0.5], (0.5, 0.75], (0.013, 0.26], (0.013, 0.26], ..., (0.26, 0.5], (0.26, 0.5], (0.013, 0.26], (0.5, 0.75], (0.26, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.013, 0.26] < (0.26, 0.5] < (0.5, 0.75] < (0.75, 0.99]]

In [108]:
data = np.random.standard_normal(1000)

In [109]:
quartiles = pd.qcut(data, 4, precision=2)

In [110]:
quartiles

[(0.0072, 0.71], (0.0072, 0.71], (0.0072, 0.71], (0.71, 3.67], (-3.0399999999999996, -0.7], ..., (0.71, 3.67], (0.71, 3.67], (-3.0399999999999996, -0.7], (0.71, 3.67], (-0.7, 0.0072]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0399999999999996, -0.7] < (-0.7, 0.0072] < (0.0072, 0.71] < (0.71, 3.67]]

In [111]:
pd.value_counts(quartiles)

/var/folders/cn/2lgryvj10c92k5wktj1wn8tr0000gp/T/ipykernel_71939/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.0399999999999996, -0.7]    250
(-0.7, 0.0072]                 250
(0.0072, 0.71]                 250
(0.71, 3.67]                   250
Name: count, dtype: int64

In [112]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.029, -1.319]    100
(-1.319, 0.0072]    400
(0.0072, 1.304]     400
(1.304, 3.668]      100
Name: count, dtype: int64

In [113]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [114]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.051156     0.007446    -0.052315    -0.029424
std       1.004858     1.040656     0.996184     0.990875
min      -3.306675    -4.231047    -3.348145    -2.969950
25%      -0.752810    -0.712346    -0.703442    -0.716703
50%      -0.045091     0.018278    -0.066514    -0.022749
75%       0.599311     0.699918     0.621188     0.626790
max       2.575290     3.028648     3.555584     3.523886

In [115]:
col = data[2]

In [116]:
col[col.abs() > 3]

494    3.555584
518   -3.348145
590   -3.075553
601   -3.110140
Name: 2, dtype: float64

In [117]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
77   0.810503 -3.376123 -0.118895  0.538750
78  -3.199967  2.510541 -0.106226 -0.072921
109 -3.306675  0.081686 -1.880565  0.803924
170 -1.347480 -4.231047 -0.400658  2.515558
306 -0.219424 -1.550701  0.427942  3.523886
494  0.086668 -0.335993  3.555584  0.120969
518  0.347869  1.076881 -3.348145 -0.073737
590 -1.349978 -0.758814 -3.075553 -0.912848
601 -1.175613  0.752442 -3.110140 -1.394824
645 -0.399955  3.028648  2.186478  0.256180
998 -1.397111 -3.118133 -0.649880  0.496494

In [118]:
data[data.abs() > 3] = np.sign(data) * 3

In [119]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.050650     0.009143    -0.052337    -0.029948
std       1.003302     1.034760     0.992668     0.989131
min      -3.000000    -3.000000    -3.000000    -2.969950
25%      -0.752810    -0.712346    -0.703442    -0.716703
50%      -0.045091     0.018278    -0.066514    -0.022749
75%       0.599311     0.699918     0.621188     0.626790
max       2.575290     3.000000     3.000000     3.000000

In [120]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0 -1.0 -1.0 -1.0
2 -1.0  1.0  1.0 -1.0
3  1.0 -1.0  1.0  1.0
4  1.0 -1.0 -1.0  1.0

In [121]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))


In [122]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [123]:
sampler = np.random.permutation(5)

In [124]:
sampler

array([1, 4, 0, 3, 2])

In [125]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [127]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [130]:
column_sampler = np.random.permutation(7)

In [132]:
column_sampler

array([0, 1, 6, 5, 3, 2, 4])

In [133]:
df.take(column_sampler, axis="columns")

0   1   6   5   3   2   4
0   0   1   6   5   3   2   4
1   7   8  13  12  10   9  11
2  14  15  20  19  17  16  18
3  21  22  27  26  24  23  25
4  28  29  34  33  31  30  32

In [134]:
df.sample(n=3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [135]:
choices = pd.Series([5, 7, -1, 6, 4])

In [136]:
choices.sample(n=10, replace=True)

2   -1
4    4
0    5
1    7
1    7
4    4
1    7
0    5
2   -1
2   -1
dtype: int64

In [137]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
   .....:                    "data1": range(6)})

In [138]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [139]:
mnames

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [140]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)

In [141]:
df_with_dummy = df[["data1"]].join(dummies)

In [142]:
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [143]:
mnames = ["movie_id", "title", "genres"]

In [144]:
movies = pd.read_table("/Users/deepa/Documents/Projects/WesCh5/pydata-book/datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")

In [145]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [146]:
dummies = movies["genres"].str.get_dummies("|")

In [147]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [148]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [149]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [150]:
np.random.seed(12345) # to make the example repeatable


In [151]:
values = np.random.uniform(size=10)

In [152]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [153]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [154]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [155]:
s = pd.Series([1, 2, 3, None])

In [156]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [157]:
s.dtype

dtype('float64')

In [158]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [159]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [160]:
s.dtype

Int64Dtype()

In [161]:
s[3]

<NA>

In [162]:
s[3] is pd.NA

True

In [163]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [164]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [165]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [166]:
df = pd.DataFrame({"A": [1, 2, None, 4],
   .....:                    "B": ["one", "two", "three", None],
   .....:                    "C": [False, None, False, True]})

In [167]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [168]:
df["A"] = df["A"].astype("Int64")


In [169]:
df["B"] = df["B"].astype("string")

In [170]:
df["C"] = df["C"].astype("boolean")

In [171]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [172]:
val = "a, b, guido"

In [173]:
val.split(",")

['a', ' b', ' guido']

In [174]:
pieces = [x.strip() for x in val.split(",")]

In [175]:
pieces

['a', 'b', 'guido']

In [176]:
first , second, third = pieces

In [177]:
first + "::" + second+ "::" + third

'a::b::guido'

In [178]:
"::".join(pieces)

'a::b::guido'

In [179]:
"guido" in val

True

In [180]:
val.index(",")

1

In [181]:
val.find(":")

-1

In [182]:
va,index(":")

NameError: name 'va' is not defined

In [183]:
val.count(",")

2

In [184]:
val.replace(",", "::")

'a:: b:: guido'

In [185]:
val.replace(",", "")

'a b guido'

In [186]:
import re

In [187]:
text = "foo   bar\t baz  \tqux"

In [192]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [205]:
result = re.findall(r"\s+", text)

In [206]:
result

['   ', '\t ', '  \t']

In [207]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive

In [208]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [209]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [210]:
m = regex.search(text)

In [211]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [212]:
text[m.start():m.end()]

'dave@google.com'

In [213]:
print(regex.match(text))

None


In [214]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [215]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [216]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [217]:
m = regex.match("wesm@bright.net")

In [218]:
m.groups()

('wesm', 'bright', 'net')

In [219]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [220]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [221]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
   .....:         "Rob": "rob@gmail.com", "Wes": np.nan}


In [222]:
data = pd.Series(data)

In [223]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [224]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [225]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [226]:
data_as_string_ext = data.astype('string')

In [227]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [228]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [229]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [230]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [231]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [232]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [233]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [234]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [235]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [236]:
values = pd.Series(['apple', 'orange', 'apple',
   .....:                     'apple'] * 2)

In [237]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [238]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [239]:
pd.value_counts(values)

/var/folders/cn/2lgryvj10c92k5wktj1wn8tr0000gp/T/ipykernel_71939/3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [240]:
values = pd.Series([0, 1, 0, 0] * 2)


In [241]:
dim = pd.Series(['apple', 'orange'])

In [242]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [243]:
dim

0     apple
1    orange
dtype: object

In [244]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [245]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [246]:
N = len(fruits)

In [247]:
rng = np.random.default_rng(seed=12345)

In [248]:
df = pd.DataFrame({'fruit': fruits,
   .....:                    'basket_id': np.arange(N),
   .....:                    'count': rng.integers(3, 15, size=N),
   .....:                    'weight': rng.uniform(0, 4, size=N)},
   .....:                   columns=['basket_id', 'fruit', 'count', 'weight'])


In [249]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [250]:
fruit_cat = df['fruit'].astype('category')

In [251]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [252]:
c = fruit_cat.array

In [253]:
type(c)

pandas.core.arrays.categorical.Categorical

In [254]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [255]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [256]:
df['fruit'] = df['fruit'].astype('category')

In [257]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [258]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [259]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [260]:
categories = ['foo', 'bar', 'baz']

In [261]:
codes = [0, 1, 2, 0, 0, 1]

In [262]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [263]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [264]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
   .....:                                         ordered=True)

In [265]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [266]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [268]:
rng = np.random.default_rng(seed=12345)

In [269]:
draws = rng.standard_normal(1000)

In [270]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [271]:
bins = pd.qcut(draws, 4)

In [272]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]